AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  WeatherAPI

  My first full serverless API
  
Resources:
  CurrentErieWeatherFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: functions/current_erie/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          api_key: '{{resolve:ssm:/weatherapi/apikey:1}}'
      Policies:
      - Statement:
        - Sid: KMSDecrypt
          Effect: Allow
          Action:
          - kms:Decrypt
          Resource: 'arn:aws:kms:us-east-1:194934475904:key/c7c3e972-ee19-4c54-8884-09ef8f50af66'
      Events:
        GetCurrentErieWeather:
          Type: Api
          Properties:
            Path: /current-erie
            Method: get